### ISSUE TITLE
2023 update

### ISSUE THREAD

**Issue by trufanov-nok** [rirze/sgp4-cpp#2]
Hi,
It seems the code got update : https://celestrak.org/software/vallado-sw.php

**Comment by rirze** [comment]
This repo is not maintained anymore. It's not automated, and a mirror like this ought to be. I would recommend someone making a fork of this repo if they want the same functionality.

**Comment by trufanov-nok** [comment]
I see. Thank's for reply. You may "mark this repository as archived and read-only" in settings for clarity.

**Comment by rirze** [comment]
Yah, I'll do that thanks. I had honestly forgotten that this repo was open still.
